add gesture_event_handler
DaniilKlieshchov/gesture-input pull request #1
Opened 2023-10-17 20:41 UTC by DaniilKlieshchov

@TheBestTvarynka

2023-10-20 17:28 UTC, TheBestTvarynka requested changes
good code. I like it

2023-10-20 17:28 UTC, TheBestTvarynka commented on Cargo.toml
> +chrono = "0.4"
`time` crate is preferred but ok

2023-10-20 17:28 UTC, TheBestTvarynka commented on config.yaml
❤️

2023-10-20 17:28 UTC, TheBestTvarynka commented on src/configuration.rs
> +    let data = fs::read_to_string("config.yaml").unwrap();
make this config path configurable

2023-10-20 17:28 UTC, TheBestTvarynka commented on src/main.rs
> +    input.udev_assign_seat("seat0").unwrap();
make this parameter configurable

2023-10-20 17:28 UTC, TheBestTvarynka commented on src/main.rs
> +                _ => {},
log this event. for example:

```rust
tracing::warn!(?event, "Got unsupported event");
```

2023-10-22 10:04 UTC, TheBestTvarynka approved these changes

2023-10-23 12:01 UTC, YuliaProkopovych approved these changes
🔥

2023-10-23 13:19 UTC, TheBestTvarynka approved these changes

2023-10-23 20:41 UTC, vsmysle approved these changes
Amazing project, I really enjoyed reviewing your code 👍

2023-10-23 20:41 UTC, vsmysle commented on config.yaml
> +      action: echo 'swiped right with 4 fingers'
As a suggestion for the future: It would be nice to have an ability to specify `pwd` and set it as a `.current_dir()` during the execution.
For example:
 ```yaml
 - !FourFingerSwipe
       direction: Right
       action: dd if=arch.iso of=/dev/sdc bs=4M; sync
       pwd: /home/kyr/isos/linux/
```

2023-10-23 20:41 UTC, vsmysle commented on src/configuration.rs
> +    let data = fs::read_to_string(path).unwrap();
It would be good to have an error handling here.

2023-10-23 20:41 UTC, vsmysle commented on src/gesture_handler.rs
> +        let listeners: Vec<Box<dyn GestureListener>> = gestures.into_iter().map(|gesture| Gesture::listen(gesture)).collect();
I think this can be simplified, but I can't test because I am on Mac:
```suggestion
        let listeners: Vec<Box<dyn GestureListener>> = gestures.into_iter().map(Gesture::listen).collect();
```

2023-10-23 20:41 UTC, vsmysle commented on src/gesture_listener.rs
> +                        }
It would be cool to have proper output in this function:
Programs can output to standard error and still return a zero exit status and I think it would be cool to check for this.
For example, to convert  to get `output.stdout` and log it with `info!` only if `stderr` is empty.

2023-10-24 06:43 UTC, TheBestTvarynka commented on src/configuration.rs
> +    let data = fs::read_to_string(path).unwrap();
config errors always happen at the start of the program. so it's ok to panic here, I think

2023-10-24 17:33 UTC, vni approved these changes
Overall it a cool project! Thank!! : ))

Have few minor points (comments are left).
Also, please run ```cargo fmt```
and also check the output of ```cargo clippy``` (it gave me some dirty output).

2023-10-24 17:33 UTC, vni commented on src/gesture_listener.rs
> +}
I believe, that this can be combined with ```ThreeFingerSwipeListener```. Just add the field for ```finger_count```.

2023-10-24 17:33 UTC, vni commented on src/gesture_listener.rs
> +}
```PinchListener``` and ```SpreadListener``` looks like the same except the scale factor (more or less then 1.0).
It's possible to combine this structures together and add scale_factor: enum { Pinch, Spread }; (this is pseudo rust).

2023-12-07 11:19 UTC, merged